
# Needed for docker
sudo: required

services: docker

# install the stable release of chefdk
addons:
  apt:
    sources:
      - chef-stable-precise
    packages:
      - chefdk

install: echo "skip bundle install"

env:
  matrix:
  - INSTANCE=default-centos-7
  - INSTANCE=default-ubuntu-1510

before_script:
  - docker --version
  - docker info
  - mount
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(/opt/chefdk/bin/chef shell-init bash)"
  - /opt/chefdk/embedded/bin/chef gem install kitchen-dokken

script:
  - /opt/chefdk/embedded/bin/chef --version
  - /opt/chefdk/embedded/bin/foodcritic . -f any
  - /opt/chefdk/embedded/bin/rspec
  - KITCHEN_YAML=.kitchen.docker.yml kitchen verify ${INSTANCE}

after_script:
  - docker images
  - docker ps -a
  - cat .kitchen/logs/*kitchen*.log
